### ISSUE TITLE
use ScreenIcon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-common#1]
Related to https://github.com/phetsims/joist/issues/626

Looking at all of the Screens in the suite that uses number-line-common...  `JOIST/ScreenIcon` should be used for screen and navbar icons.

**Comment by pixelzoom** [comment]
The easiest way to address this is to wrap your existing Node with ScreenIcon.  For example in NLIExploreScreen:

```js
      homeScreenIcon: new ScreenIcon( new Image( exploreScreenHomeIcon ), {
        maxIconWidthProportion: 1,
        maxIconHeightProportion: 1
      } ),
      navigationBarIcon: new ScreenIcon( new Image( exploreScreenNavIcon ), {
        maxIconWidthProportion: 1,
        maxIconHeightProportion: 1
      } ),
```

**Comment by jbphet** [comment]
number-line-integers and number-line-operations have been converted, closing.
