### ISSUE TITLE
CT: Usages of SpatializedNumberLine are failing to construct due to changes related to enumerations

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-common#4]
All three of the sims in the Number Line Suite are failing on CT, and my initial investigation shows that this is related to usages of `Orientation.ts` in conjunction with `EnumerationDeprecatedProperty.js`.  It seems like the bulk of the recent changes were made by @zepumph, so I'm assigning this to him.

Screenshot of CT filtered on "number-line":

![image](https://user-images.githubusercontent.com/3082831/149585228-a0971cb7-f040-407c-9805-995ab37d9ad9.png)

**Comment by jbphet** [comment]
I took a preliminary look at this, and the failure is occurring in `EnumerationDeprecatedProperty` when it tries to validate that the initial value of the property is a valid value for the enumeration.

**Comment by samreid** [comment]
I'll take a look now.

**Comment by samreid** [comment]
I pushed a proposed fix that seems to correct it locally, at least for number-line-distance.

**Comment by zepumph** [comment]
Yes thanks for that! I assumed that this would happen a lot in the future when converting, so I made a bit more friendly of an assertion. Closing

**Comment by jbphet** [comment]
PS - CT is now clear.
